openapi: '3.0.3'
info:
  description: APIs for Placing order, fetch and reporting
  title:  Order placement and management  Api
  version: '3.0.0'


servers:
  - url: http://localhost:8085/api/v1/products
    description: Base path of the API products




tags:
  - name: OrderPlace
    description: APIs for place order
security:
  - basicAuth: []

paths: {
  '/fetchProducts': {
    get: {
      'operationId': 'fetchProducts',
      'description': 'API to return all avilable products',
      'parameters': [
        {
          'name': 'products',
          'in': 'query',
          'required': false,
          'description': 'proucts to be searched',
          'schema': {
            'type': 'string',
            'example': 'Shirt'
          }
        }
      ],

      'responses': {
        '200': {
          'description': 'successful return of all products',
          'content': {
            'application/json': {
              'schema': {
                '$ref': '#/components/schemas/ProductDTO'
              }
            }
          }
        },

        '204': {
          description: No products returned
        },

        '403': {
          '$ref': '#/components/responses/AuthorizationException'
        }
      }}

  },

  '/placeOrder': {
    post: {
      'operationId': 'placeOrder',
      'description': 'API to return place an order',
      'requestBody':
        {
          'required':true,
          'description': 'params required to place an order',
          'content': {
            'application/json': {
              'schema': {
                '$ref': '#/components/schemas/OrderDto'
              }
            }
          }
        },
      'responses': {
        '201': {
          'description': 'successful creation of an of a recipie',
          'content': {
            'application/json': {
              'schema': {
                type: string,
                example: Your order has been placed successfully and the id is 1
              }
            }
          }
        },
        '401': {
          '$ref': '#/components/responses/AuthenticationException'
        },
        '403': {
          '$ref': '#/components/responses/AuthorizationException'
        },
        '404': {
          '$ref': '#/components/responses/ProductNotFoundException'
        },
        '500': {
          '$ref': '#/components/responses/Exception'
        },
        '400': {
          '$ref': '#/components/responses/BadRequestException'
        }
      }}
  }

}

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  responses:
    AuthenticationException:
      description: when an invalid credentials is supplied
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            error: Invalid credentials supplied
    AuthorizationException:
      description: the user when doesnt have privillage
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            error: Access denied due to insufficient privilage

    ProductNotFoundException:
      description: when the request product to be created is not available
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            error: Product shoe not found for the brand puma by the seller bol

    BadRequestException:
      description: when the request is incorrect
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            error: Invalid phone number

    Exception:
      description: All generic exception
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            error: Technical issues when operation is performed

  schemas:
    Errors:
      type: object
      properties:
        status:
          description: 'status of the error code'
          type: integer
        message:
          description: 'error message'
          type: string
        timestamp:
          description: 'timestamp value during when exception occured'
          type: string



    ProductDTO:
      type: object
      properties:
        productName:
          description: 'Name of the product'
          type: integer
        brand:
          description: 'brand name of the product'
          type: string
        stockleft:
          description: 'Available stock in the market'
          type: string
        price:
          description: 'price of the product'
          type: string
        currency:
          description: 'Currency type  of the price of the product'
          type: string
        seller:
          description: 'seller name'
          type: string


    OrderDto:
      type: object
      properties:
        customerName:
          description: 'Person who places the order'
          type: string
        mobileNumber:
          description: 'contact number of the person'
          type: string
        products:
          description: 'Available stock in the market'
          type: array
          items:
            $ref: '#/components/schemas/ProductOrderDto'

    ProductOrderDto:
      type: object
      properties:
        productName:
          description: 'name of the product'
          type: string
        seller:
          description: 'name of the seller'
          type: string
        brand:
          description: 'brand name of the product'
          type: string
        quantity:
          description: 'quantity of items'
          type: string