services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ProductOrders
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin@123
    ports:
      - "3306:3306"
